version: 3.7
services:

  server:
    container_name: famre-server
    image: efenstakes/famre
    restart: always
    build: .
    ports:
      - '81:3456'

  db:
    container_name: famre-db
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - famre-db-backup:/data/db

volumes:
  famre-db-backup: